### ISSUE TITLE
Dark mode: campo input de tarefa não mudou a cor antes de adicionar tarefa.

### ISSUE THREAD

**Issue by viniciusgferreira** [KarineBrandelli/to-do-app#6]
![image](https://user-images.githubusercontent.com/30271243/204090987-422e2952-a8ed-4c37-9c92-e085af102ba5.png)
![image](https://user-images.githubusercontent.com/30271243/204091012-ff52629a-f6c4-4f89-a303-cd2e1a799dfc.png)

**Comment by KarineBrandelli** [comment]
Obrigada pela dica! Vou verificar assim que possível.

**Comment by KarineBrandelli** [comment]
Adicionei a condição 'color: var(--color-texts);' ao input e funcionou.
